version: 2
updates:
  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
    ignore:
      - dependency-name: "node"
        versions: [">= 23.0"]
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
