version: "3.7"

services:

  logging:
    container_name: tisronclicom-logging
    build: ./logging
    ports:
      - "12201:12201/udp"
    environment:
      PORT: 12201
      APPINSIGHTS_PERFORMANCE_METRICS: 0
      APPINSIGHTS_CONNECTIONSTRING: /run/secrets/APPINSIGHTS_CONNECTIONSTRING
    secrets:
      - APPINSIGHTS_CONNECTIONSTRING
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /var/logging/start.sh

  node:
    container_name: tisronclicom-node
    build:
      context: ./node
      args:
        USE_AZURE_FILE_STORAGE: 1
    depends_on:
      - logging
    networks:
      - tis.roncli.com-network
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      PORT: 3030
      NODE_ENV: production
      APPINSIGHTS_CONNECTIONSTRING: /run/secrets/APPINSIGHTS_CONNECTIONSTRING
      FILES_URI: /run/secrets/FILES_URI
      FILES_USERNAME: /run/secrets/FILES_USERNAME
      FILES_PASSWORD: /run/secrets/FILES_PASSWORD
      USE_AZURE_FILE_STORAGE: 1
    secrets:
      - APPINSIGHTS_CONNECTIONSTRING
      - FILES_URI
      - FILES_USERNAME
      - FILES_PASSWORD
    restart: always
    entrypoint: /var/www/start.sh
    privileged: true

  nginx:
    container_name: tisronclicom-nginx
    build: ./nginx
    depends_on:
      - node
      - logging
    networks:
      - tis.roncli.com-network
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      DOMAIN: tis.roncli.com
      PROXY_PORT: 3030
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-work:/var/certbot/work:rw
      - nginx-work:/var/nginx/work:rw
    entrypoint: /var/nginx/start.sh

  certbot:
    container_name: tisronclicom-certbot
    build: ./certbot
    depends_on:
      - nginx
      - logging
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      DOMAIN: tis.roncli.com
      EMAIL: roncli@roncli.com
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-work:/var/certbot/work:rw
    entrypoint: /var/certbot/start.sh

networks:
  tis.roncli.com-network:
    driver: bridge

volumes:
  certbot-conf:
  certbot-work:
  nginx-work:

secrets:
  APPINSIGHTS_CONNECTIONSTRING:
    file: ./secrets/APPINSIGHTS_CONNECTIONSTRING
  FILES_URI:
    file: ./secrets/FILES_URI
  FILES_USERNAME:
    file: ./secrets/FILES_USERNAME
  FILES_PASSWORD:
    file: ./secrets/FILES_PASSWORD
