version: "3.7"

services:

  node:
    container_name: tisronclicom-node
    build: ./node
    networks:
      - tis.roncli.com-network
    environment:
      PORT: 3030
      NODE_ENV: production
      FILES_URI: /run/secrets/FILES_URI
      FILES_USERNAME: /run/secrets/FILES_USERNAME
      FILES_PASSWORD: /run/secrets/FILES_PASSWORD
    secrets:
      - FILES_URI
      - FILES_USERNAME
      - FILES_PASSWORD
    restart: always
    entrypoint: /var/www/start.sh
    privileged: true

  nginx:
    container_name: tisronclicom-nginx
    build: ./nginx
    depends_on:
      - node
    networks:
      - tis.roncli.com-network
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: tis.roncli.com
      PROXY_PORT: 3030
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-work:/var/certbot/work:rw
      - nginx-work:/var/nginx/work:rw
    entrypoint: /var/nginx/start.sh

  certbot:
    container_name: tisronclicom-certbot
    build: ./certbot
    depends_on:
      - nginx
    environment:
      DOMAIN: tis.roncli.com
      EMAIL: roncli@roncli.com
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-work:/var/certbot/work:rw
    entrypoint: /var/certbot/start.sh

networks:
  tis.roncli.com-network:
    driver: bridge

volumes:
  certbot-conf:
  certbot-work:
  nginx-work:

secrets:
  FILES_URI:
    file: ./secrets/FILES_URI
  FILES_USERNAME:
    file: ./secrets/FILES_USERNAME
  FILES_PASSWORD:
    file: ./secrets/FILES_PASSWORD
