// Minimal CommonJS-compatible types for html-minifier-terser.
declare module "html-minifier-terser" {
    /**
     * Most of the options are disabled by default
     */
    export interface Options {
        caseSensitive?: boolean | undefined;
        collapseBooleanAttributes?: boolean | undefined;
        collapseInlineTagWhitespace?: boolean | undefined;
        collapseWhitespace?: boolean | undefined;
        conservativeCollapse?: boolean | undefined;
        continueOnParseError?: boolean | undefined;
        customAttrAssign?: RegExp[] | undefined;
        customAttrCollapse?: RegExp | undefined;
        customAttrSurround?: RegExp[] | undefined;
        customEventAttributes?: RegExp[] | undefined;
        decodeEntities?: boolean | undefined;
        html5?: boolean | undefined;
        ignoreCustomComments?: RegExp[] | undefined;
        ignoreCustomFragments?: RegExp[] | undefined;
        includeAutoGeneratedTags?: boolean | undefined;
        keepClosingSlash?: boolean | undefined;
        maxLineLength?: number | undefined;
        minifyCSS?: boolean | object | ((text: string, type?: string) => string) | undefined;
        minifyJS?: boolean | object | ((text: string, inline?: boolean) => string) | undefined;
        minifyURLs?: boolean | string | object | ((text: string) => string) | undefined;
        noNewlinesBeforeTagClose?: boolean | undefined;
        preserveLineBreaks?: boolean | undefined;
        preventAttributesEscaping?: boolean | undefined;
        processConditionalComments?: boolean | undefined;
        processScripts?: string[] | undefined;
        quoteCharacter?: string | undefined;
        removeAttributeQuotes?: boolean | undefined;
        removeComments?: boolean | undefined;
        removeEmptyAttributes?: boolean | ((attrName: string, tag: string) => boolean) | undefined;
        removeEmptyElements?: boolean | undefined;
        removeOptionalTags?: boolean | undefined;
        removeRedundantAttributes?: boolean | undefined;
        removeScriptTypeAttributes?: boolean | undefined;
        removeStyleLinkTypeAttributes?: boolean | undefined;
        removeTagWhitespace?: boolean | undefined;
        sortAttributes?: boolean | undefined;
        sortClassName?: boolean | undefined;
        trimCustomFragments?: boolean | undefined;
        useShortDoctype?: boolean | undefined;
    }

    export function minify(value: string, options?: Options): Promise<string>
}
